from snakemake.io import directory

debug = config["debug"]
local = config["local"]
full_scale = config["full_scale"]

rule artifact_for_lbwsg_pafs:
    input: config["env_input"] + ["0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/data/loader.py"]
    output: ["0300_child_sim/lbwsg_paf_mean_draw_artifacts/{location}.hdf"]
    shell:
        f"""
        {config["env_setup"]}
        cd 0300_child_sim
        rm -f lbwsg_paf_mean_draw_artifacts/{{wildcards.location}}.hdf
        export PYTHONPATH=./src
        python src/vivarium_gates_lsff_by_wealth_quintile_child/tools/cli.py -o ./lbwsg_paf_mean_draw_artifacts -l {{wildcards.location}} --for-lbwsg-pafs --national -a --mean {'--pdb -vvv' if debug else ''}
        """

rule lbwsg_pafs:
    input: config["simulation_running_env_input"] + ["0300_child_sim/lbwsg_paf_mean_draw_artifacts/{location}.hdf", "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf.yaml", "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf_branches.yaml"]
    output: ["0300_child_sim/lbwsg_pafs/{location}/calculated_lbwsg_paf_on_cause.diarrheal_diseases.excess_mortality_rate.parquet"]
    shell:
        f"""
        {config["simulation_running_env_setup"]}
        cd 0300_child_sim
        rm -rf lbwsg_pafs/{{wildcards.location}} || true
        sleep 5
        rm -rf lbwsg_pafs/{{wildcards.location}}
        rm -f dump.rdb
        export PYTHONPATH=./src
        {'python ../local_' if local else ''}{'p' if not debug else ''}simulate{'.py' if local else ' run'} src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf.yaml {'src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf_branches.yaml' if not debug else ''} -i lbwsg_paf_mean_draw_artifacts/{{wildcards.location}}.hdf -o lbwsg_pafs/ {'-P proj_simscience -m 2 -r 01:00:00 -q all.q' if not debug and not local else ''} {'--pdb -vvv' if debug and not local else ''}
        mv lbwsg_pafs/{{wildcards.location}}/*/results/*.parquet lbwsg_pafs/{{wildcards.location}}
        """


rule child_artifacts:
    input: 
        config["env_input"] + [
            "0300_child_sim/lbwsg_pafs/{location}/calculated_lbwsg_paf_on_cause.diarrheal_diseases.excess_mortality_rate.parquet",
            "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/data/loader.py",
            "0200_pregnancy_sim/sim_results/{vehicle}/{location}/births.parquet",
            "0100_data_prep/results/birth_weight_disparities/{location}.csv",
            "0100_data_prep/results/iron/fortification_birthweight_effects.csv"
        ]
    output: ["0300_child_sim/mean_draw_artifacts/{vehicle}/{location}.hdf"]
    shell:
        f"""
        {config["env_setup"]}
        cd 0300_child_sim
        rm -f mean_draw_artifacts/{{wildcards.vehicle}}/{{wildcards.location}}.hdf
        export PYTHONPATH=./src
        python src/vivarium_gates_lsff_by_wealth_quintile_child/tools/cli.py -o ./mean_draw_artifacts/{{wildcards.vehicle}} -l {{wildcards.location}} --vehicle {{wildcards.vehicle}} --fertility-data-path ../0200_pregnancy_sim/sim_results/{{wildcards.vehicle}}/{{wildcards.location}}/births.parquet --national -a --mean {'--pdb -vvv' if debug else ''}
        """

import glob
code_inputs = glob.glob("0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/**/*.py")

rule child_simulations:
    input:
        config["simulation_running_env_input"] + [
            "0300_child_sim/mean_draw_artifacts/{vehicle}/{location}.hdf",
            "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/model_spec.yaml",
            "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/branches/scenarios" + ('_small' if not full_scale else '') + ".yaml",
        ] + code_inputs
    output:
        [
            directory("0300_child_sim/sim_results/{vehicle}/{location}/"),
            "0300_child_sim/sim_results/{vehicle}/{location}/person_time.parquet",
            "0300_child_sim/sim_results/{vehicle}/{location}/deaths.parquet",
            "0300_child_sim/sim_results/{vehicle}/{location}/ylds.parquet",
            "0300_child_sim/sim_results/{vehicle}/{location}/ylls.parquet",
            "0300_child_sim/sim_results/{vehicle}/{location}/birth_weight_sum.parquet",
            "0300_child_sim/sim_results/{vehicle}/{location}/live_births.parquet",
        ]
    shell:
        f"""
        {config["simulation_running_env_setup"]}
        cd 0300_child_sim
        # NFS sometimes doesn't delete right away
        rm -rf sim_results/{{wildcards.vehicle}}/{{wildcards.location}} || true
        sleep 5
        rm -rf sim_results/{{wildcards.vehicle}}/{{wildcards.location}}
        mkdir -p sim_results/{{wildcards.vehicle}}/{{wildcards.location}}
        cd sim_results/{{wildcards.vehicle}}/{{wildcards.location}}
        export PYTHONPATH=../../../src
        {'python ../../../../local_' if local else ''}{'p' if not debug else ''}simulate{'.py' if local else ' run'} ../../../src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/model_spec.yaml {'../../../src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/branches/scenarios' + ('_small' if not full_scale else '') + '.yaml' if not debug else ''} -i ../../../mean_draw_artifacts/{{wildcards.vehicle}}/{{wildcards.location}}.hdf -o .. {'-P proj_simscience -m 2 -r 01:00:00 -q all.q' if not debug and not local else ''} {'--pdb -vvv' if debug and not local else ''}
        rm -f dump.rdb
        {'# ' if debug or local else ''}psimulate restart * -P proj_simscience -m 2 -r 01:00:00 -q all.q
        mv ./*/results/*.parquet .
        """
