from snakemake.io import directory

locations = [
    "India",
    "Nigeria",
    "Ethiopia",
]

rule all:
    input: [f"sim_results/{location.lower()}/deaths.parquet" for location in locations]

rule artifact_for_lbwsg_pafs:
    input: ["src/vivarium_gates_lsff_by_wealth_quintile_child/data/loader.py"]
    output: ["lbwsg_paf_artifacts/{location}.hdf"]
    shell:
        f"""
        source artifact_building/bin/activate
        make_artifacts -vvv --pdb -o ./lbwsg_paf_artifacts -l {{wildcards.location}} --no-lbwsg-pafs --national -a
        """

rule lbwsg_pafs:
    input: ["lbwsg_paf_artifacts/{location}.hdf", "src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf.yaml", "src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf_branches.yaml"]
    output: ["lbwsg_pafs/{location}/calculated_lbwsg_paf_on_cause.diarrheal_diseases.excess_mortality_rate.parquet"]
    shell:
        f"""
        rm -rf lbwsg_pafs/{{wildcards.location}}
        source simulation_running/bin/activate
        psimulate run src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf.yaml src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf_branches.yaml -i {{input[0]}} -o lbwsg_pafs/ -P proj_simscience
        mv lbwsg_pafs/{{wildcards.location}}/*/results/*.parquet lbwsg_pafs/{{wildcards.location}}
        """

rule artifacts:
    input: ["lbwsg_pafs/{location}/calculated_lbwsg_paf_on_cause.diarrheal_diseases.excess_mortality_rate.parquet", "src/vivarium_gates_lsff_by_wealth_quintile_child/data/loader.py"]
    output: ["artifacts/{location}.hdf"]
    shell:
        f"""
        source artifact_building/bin/activate
        make_artifacts -vvv -o ./artifacts -l {{wildcards.location}} --national -a
        """

rule simulations:
    input: ["artifacts/{location}.hdf", "src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/model_spec.yaml"]
    output: ["sim_results/{location}/deaths.parquet"]
    shell:
        f"""
        rm -rf sim_results/{{wildcards.location}}
        source simulation_running/bin/activate
        simulate run src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/model_spec.yaml -i {{input[0]}} -o sim_results/
        mv sim_results/{{wildcards.location}}/*/results/*.parquet sim_results/{{wildcards.location}}
        """