from snakemake.io import directory

import os

use_psimulate = not "NO_PSIMULATE" in os.environ

rule child_artifact_building_venv:
    input: ["0300_child_sim/artifact_building_pip_lock.txt"]
    output: [directory("0300_child_sim/artifact_building/"), "0300_child_sim/artifact_building/bin/activate"]
    shell:
        f"""
        cd 0300_child_sim
        rm -rf artifact_building
        python -m venv artifact_building
        source artifact_building/bin/activate
        pip install -r artifact_building_pip_lock.txt
        pip install -e .[data]
        """

rule child_simulation_running_venv:
    input: ["0300_child_sim/simulation_running_pip_lock.txt"]
    output: [directory("0300_child_sim/simulation_running/"), "0300_child_sim/simulation_running/bin/activate"]
    shell:
        f"""
        cd 0300_child_sim
        rm -rf simulation_running
        python -m venv simulation_running
        source simulation_running/bin/activate
        pip install -r simulation_running_pip_lock.txt
        pip install -e .[dev]
        """

rule artifact_for_lbwsg_pafs:
    input: ["0300_child_sim/artifact_building/bin/activate", "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/data/loader.py"]
    output: ["0300_child_sim/lbwsg_paf_artifacts/{location}.hdf"]
    shell:
        f"""
        cd 0300_child_sim
        source artifact_building/bin/activate
        rm -f lbwsg_paf_artifacts/{{wildcards.location}}.hdf
        make_artifacts -vvv -o ./lbwsg_paf_artifacts -l {{wildcards.location}} --for-lbwsg-pafs --national -a
        """

rule mean_draw_artifact_for_lbwsg_pafs:
    input: ["0300_child_sim/lbwsg_paf_artifacts/{location}.hdf", "convert_artifact_to_mean_draw.py"]
    output: ["0300_child_sim/lbwsg_paf_mean_draw_artifacts/{location}.hdf"]
    shell:
        f"""
        cd 0300_child_sim
        source artifact_building/bin/activate
        rm -f lbwsg_paf_mean_draw_artifacts/{{wildcards.location}}.hdf
        python ../convert_artifact_to_mean_draw.py lbwsg_paf_artifacts/{{wildcards.location}}.hdf lbwsg_paf_mean_draw_artifacts/{{wildcards.location}}.hdf
        """

rule lbwsg_pafs:
    input: ["0300_child_sim/simulation_running/bin/activate", "0300_child_sim/lbwsg_paf_mean_draw_artifacts/{location}.hdf", "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf.yaml", "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf_branches.yaml"]
    output: ["0300_child_sim/lbwsg_pafs/{location}/calculated_lbwsg_paf_on_cause.diarrheal_diseases.excess_mortality_rate.parquet"]
    shell:
        f"""
        cd 0300_child_sim
        rm -rf lbwsg_pafs/{{wildcards.location}} || true
        sleep 5
        rm -rf lbwsg_pafs/{{wildcards.location}}
        source simulation_running/bin/activate
        rm -f dump.rdb
        {'p' if use_psimulate else ''}simulate run src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf.yaml {'src/vivarium_gates_lsff_by_wealth_quintile_child/data/lbwsg_paf_branches.yaml' if use_psimulate else ''} -i lbwsg_paf_mean_draw_artifacts/{{wildcards.location}}.hdf -o lbwsg_pafs/ {'-P proj_simscience' if use_psimulate else ''} -vvv -q long.q
        mv lbwsg_pafs/{{wildcards.location}}/*/results/*.parquet lbwsg_pafs/{{wildcards.location}}
        """

rule child_artifacts:
    input: 
        [
            "0300_child_sim/artifact_building/bin/activate",
            "0300_child_sim/lbwsg_pafs/{location}/calculated_lbwsg_paf_on_cause.diarrheal_diseases.excess_mortality_rate.parquet",
            "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/data/loader.py",
            "0200_pregnancy_sim/sim_results/{location}/births.parquet",
        ]
    output: ["0300_child_sim/artifacts/{location}.hdf"]
    shell:
        f"""
        cd 0300_child_sim
        source artifact_building/bin/activate
        rm -f artifacts/{{wildcards.location}}.hdf
        make_artifacts -vvv -o ./artifacts -l {{wildcards.location}} --national -a
        """

rule child_mean_draw_artifacts:
    input: ["0300_child_sim/artifacts/{location}.hdf", "convert_artifact_to_mean_draw.py"]
    output: ["0300_child_sim/mean_draw_artifacts/{location}.hdf"]
    shell:
        f"""
        cd 0300_child_sim
        source artifact_building/bin/activate
        rm -f mean_draw_artifacts/{{wildcards.location}}.hdf
        python ../convert_artifact_to_mean_draw.py artifacts/{{wildcards.location}}.hdf mean_draw_artifacts/{{wildcards.location}}.hdf
        """

import glob

code_inputs = glob.glob("0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/**/*.py")
data_inputs = glob.glob("0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/**/*.csv")

rule child_simulations:
    input:
        [
            "0300_child_sim/simulation_running/bin/activate",
            "0300_child_sim/mean_draw_artifacts/{location}.hdf",
            "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/model_spec.yaml",
            "0300_child_sim/src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/branches/scenarios.yaml",
        ] + code_inputs + data_inputs
    output: [
        "0300_child_sim/sim_results/{location}/deaths.parquet",
        "0300_child_sim/sim_results/{location}/ylds.parquet",
        "0300_child_sim/sim_results/{location}/ylls.parquet",
    ]
    shell:
        f"""
        cd 0300_child_sim
        # NFS sometimes doesn't delete right away
        rm -rf sim_results/{{wildcards.location}} || true
        sleep 5
        rm -rf sim_results/{{wildcards.location}}
        source simulation_running/bin/activate
        rm -f dump.rdb
        {'p' if use_psimulate else ''}simulate run src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/model_spec.yaml {'src/vivarium_gates_lsff_by_wealth_quintile_child/model_specifications/branches/scenarios.yaml' if use_psimulate else ''} -i mean_draw_artifacts/{{wildcards.location}}.hdf -o sim_results/ {'-P proj_simscience' if use_psimulate else ''} -vvv -q long.q
        mv sim_results/{{wildcards.location}}/*/results/*.parquet sim_results/{{wildcards.location}}
        """