from snakemake.io import directory

import glob

debug = config["debug"]
local = config["local"]
full_scale = config["full_scale"]

data_inputs = [
    f"0100_data_prep/results/{item}/{{location}}.csv"
    for item in [
        "iron/{vehicle}/baseline_fortification/any_coverage",
        "iron/{vehicle}/baseline_fortification/full_coverage",
        "iron/{vehicle}/baseline_fortification/partial_coverage_amount/mean",
        "iron/{vehicle}/baseline_fortification/partial_coverage_amount/sd",
        "iron/{vehicle}/baseline_fortification/concentration",
        "{vehicle}/vehicle_consumption/any",
        "{vehicle}/vehicle_consumption/fortifiability",
        "{vehicle}/vehicle_consumption/amount/mean",
        "{vehicle}/vehicle_consumption/amount/sd",
        "iron/{vehicle}/intervention/intervention_fortification/any_coverage",
        "iron/{vehicle}/intervention/intervention_fortification/effectiveness",
        "iron/{vehicle}/intervention/intervention_fortification/concentration",
        "maternal_disorders_incidence_disparities",
        "hemoglobin/mean_disparities",
        "hemoglobin/sd_disparities",
        "wealth_quintile_probabilities",
        "pregnancy/incidence",
    ]
] + [f"0100_data_prep/results/iron/fortification_hemoglobin_effects.csv"]

rule pregnancy_artifacts:
    input: config["env_input"] + ["0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/data/loader.py"] + data_inputs
    output: ["0200_pregnancy_sim/mean_draw_artifacts/{vehicle}/{location}.hdf"]
    shell:
        f"""
        {config["env_setup"]}
        cd 0200_pregnancy_sim
        rm -f artifacts/{{wildcards.vehicle}}/{{wildcards.location}}.hdf
        export PYTHONPATH=./src
        python src/vivarium_gates_lsff_by_wealth_quintile/tools/cli.py -o ./mean_draw_artifacts/{{wildcards.vehicle}} -l {{wildcards.location}} --vehicle {{wildcards.vehicle}} -a --mean {'--pdb -vvv' if debug else ''}
        """

code_inputs = glob.glob("0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/**/*.py")

rule pregnancy_simulations:
    input:
        config["simulation_running_env_input"] + [
            "0200_pregnancy_sim/mean_draw_artifacts/{vehicle}/{location}.hdf",
            "0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/model_specifications/model_spec.yaml",
            "0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/model_specifications/branches/scenarios" + ('_small' if not full_scale else '') + ".yaml",
        ] + code_inputs + data_inputs
    output:
        [
            directory("0200_pregnancy_sim/sim_results/{vehicle}/{location}/"),
            "0200_pregnancy_sim/sim_results/{vehicle}/{location}/births.parquet",
            "0200_pregnancy_sim/sim_results/{vehicle}/{location}/deaths.parquet",
            "0200_pregnancy_sim/sim_results/{vehicle}/{location}/pregnancy_outcome_count.parquet",
            "0200_pregnancy_sim/sim_results/{vehicle}/{location}/transition_count_maternal_disorders.parquet",
            "0200_pregnancy_sim/sim_results/{vehicle}/{location}/ylds.parquet",
            "0200_pregnancy_sim/sim_results/{vehicle}/{location}/ylls.parquet",
            "0200_pregnancy_sim/sim_results/{vehicle}/{location}/person_time_anemia.parquet",
        ]
    shell:
        f"""
        {config["simulation_running_env_setup"]}
        cd 0200_pregnancy_sim
        rm -rf sim_results/{{wildcards.vehicle}} || true
        sleep 5
        rm -rf sim_results/{{wildcards.vehicle}}
        mkdir -p sim_results/{{wildcards.vehicle}}/{{wildcards.location}}
        cd sim_results/{{wildcards.vehicle}}/{{wildcards.location}}
        export PYTHONPATH=../../../src
        {'python ../../../../local_' if local else ''}{'p' if not debug else ''}simulate{'.py' if local else ' run'} ../../../src/vivarium_gates_lsff_by_wealth_quintile/model_specifications/model_spec.yaml {'../../../src/vivarium_gates_lsff_by_wealth_quintile/model_specifications/branches/scenarios' + ('_small' if not full_scale else '') + '.yaml' if not debug else ''} -i ../../../mean_draw_artifacts/{{wildcards.vehicle}}/{{wildcards.location}}.hdf -o .. {'-P proj_simscience -m 2 -r 01:00:00 -q long.q' if not debug and not local else ''} {'--pdb -vvv' if debug and not local else ''}
        rm -rf *.rdb
        {'# ' if debug or local else ''}psimulate restart * -P proj_simscience -m 2 -r 01:00:00 -q long.q
        mv ./*/results/*.parquet .
        """
