from snakemake.io import directory

rule data_prep_venv:
    input: ["0100_data_prep/data_prep_pip_lock.txt"]
    output: [directory("0100_data_prep/.venv/"), "0100_data_prep/.venv/bin/activate"]
    shell:
        f"""
        cd 0100_data_prep
        rm -rf .venv
        python -m venv .venv
        source .venv/bin/activate
        pip install -r data_prep_pip_lock.txt
        """

rule nigeria_dhs:
    input:
        [
            "0100_data_prep/.venv/bin/activate",
            "0100_data_prep/dhs/nigeria.ipynb",
        ]
    log: "0100_data_prep/executed/dhs/nigeria.ipynb"
    output: 
        [
            "0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/data/raw_data/maternal_disorders_incidence_disparities/nigeria.csv",
            "0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/data/raw_data/mean_hemoglobin_disparities/nigeria.csv",
            "0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/data/raw_data/sd_hemoglobin_disparities/nigeria.csv",
            "0200_pregnancy_sim/src/vivarium_gates_lsff_by_wealth_quintile/data/raw_data/wealth_quintile_probabilities/nigeria.csv",
        ]
    shell:
        """
        cd 0100_data_prep
        source .venv/bin/activate
        cd dhs
        papermill nigeria.ipynb ../executed/dhs/nigeria.ipynb -k python3
        """