debug = config["debug"]

def non_pregnant_anemia_inputs(wildcards):
    return (
        config["env_input"] + [
            "0400_non_pregnant_anemia_model/non_pregnant_anemia.ipynb",
            "0100_data_prep/results/iron/fortification_hemoglobin_effects.csv",
            "0100_data_prep/results/iron/{vehicle}/baseline_fortification/effective_coverage/{location}.csv",
            "0100_data_prep/results/population/stratified/{location}.csv",
            "0100_data_prep/results/hemoglobin/mean_disparities/{location}.csv",
            "0100_data_prep/results/hemoglobin/sd_disparities/{location}.csv",
            "0100_data_prep/results/wealth_quintile_probabilities/{location}.csv",
        ] + [
            f"0100_data_prep/results/iron/{{vehicle}}/{intervention_scenario}/intervention_fortification/effective_coverage/{{location}}.csv"
            for intervention_scenario in config["custom_intervention_scenarios"].get(wildcards.location, ["intervention"])
        ]
    )

rule non_pregnant_anemia:
    input: non_pregnant_anemia_inputs
    output:
        [
            "0400_non_pregnant_anemia_model/results/{vehicle}/{location}/ylds.parquet",
            "0400_non_pregnant_anemia_model/results/{vehicle}/{location}/anemia_prevalence.parquet",
            "0400_non_pregnant_anemia_model/results/{vehicle}/{location}/anemia_cases.parquet",
        ]
    log: "0400_non_pregnant_anemia_model/executed/{vehicle}/{location}/non_pregnant_anemia.ipynb"
    shell:
        f"""
        {config["env_setup"]}
        cd 0400_non_pregnant_anemia_model
        mkdir -p ../executed/{{wildcards.vehicle}}/{{wildcards.location}}
        papermill non_pregnant_anemia.ipynb ./executed/{{wildcards.vehicle}}/{{wildcards.location}}/non_pregnant_anemia.ipynb -p location {{wildcards.location}} -p vehicle {{wildcards.vehicle}} -k python3 {'--engine debug' if debug else ''}
        """

from snakemake.io import Wildcards

def non_pregnant_anemia_ethiopia_folate_inputs(wildcards):
    return [x.replace('{location}', 'ethiopia').replace('iron', 'folate').replace('.ipynb', '_folate.ipynb') for x in non_pregnant_anemia_inputs(Wildcards(fromdict={**wildcards, 'location': 'ethiopia'})) if 'fortification_hemoglobin_effects' not in x]

rule non_pregnant_anemia_ethiopia_folate:
    input: non_pregnant_anemia_ethiopia_folate_inputs
    output:
        [
            "0400_non_pregnant_anemia_model/results/{vehicle}/ethiopia/ylds.parquet",
            "0400_non_pregnant_anemia_model/results/{vehicle}/ethiopia/anemia_prevalence.parquet",
            "0400_non_pregnant_anemia_model/results/{vehicle}/ethiopia/anemia_cases.parquet",
        ]
    log: "0400_non_pregnant_anemia_model/executed/{vehicle}/ethiopia/non_pregnant_anemia_folate.ipynb"
    shell:
        f"""
        {config["env_setup"]}
        cd 0400_non_pregnant_anemia_model
        mkdir -p ../executed/{{wildcards.vehicle}}/ethiopia
        papermill non_pregnant_anemia_folate.ipynb ./executed/{{wildcards.vehicle}}/ethiopia/non_pregnant_anemia_folate.ipynb -p location ethiopia -p vehicle {{wildcards.vehicle}} -k python3 {'--engine debug' if debug else ''}
        """

ruleorder: non_pregnant_anemia_ethiopia_folate > non_pregnant_anemia